### PR TITLE
Add a way to fetch top videos

### PR DESCRIPTION
**Pull request by brianegan**
Scary amount of additions, mostly due to the json, but really just a small amount of rearranging the models / json parsing to accommodate a growing # of value classes + adding a way to fetch the top videos.

Probs easiest to start with the tests and then look at the file structure changes in an IDE to see if they make sense.

### CODE REVIEW

**Comment by brianegan** [comment]
I think there might be a slight CI config issue. It's trying to run the `sanity_check.dart` script, but cannot pull the correct variables from the environment when running `new TwitchHttp.fromEnv();`. Could you please help me correct this problem with Travis? Might not be best to add the `envs` as I've done in the travis.yml as a temporary measure.

**Comment by matanlurey** [comment]
Everything looks OK to me. Unless it broke `sanity_check.dart` should automatically be using the token I have stored on travis. Could you try removing the entire `env: ` section and try again?

**Review by matanlurey — APPROVED** [review]

**Comment by brianegan** [comment]
Hrm, just did a `git reset --hard~1`, `git commit --amend` and re-pushed to trigger a new build and got the same result :(

```bash
0.48s$ dart tool/sanity_check.dart
Error: Bad state: Could not read "TWITCH_CLIENT_ID".
Stack: package:twitch/src/http.dart 83:7  TwitchHttp.TwitchHttp.fromEnv
tool/sanity_check.dart 21:16       main
```

**Comment by matanlurey** [comment]
I'll merge, we can fix upstream. Thanks @brianegan!

**Pull request merged**
